# Generated by Django 3.0.4 on 2020-03-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapp', '0002_auto_20200318_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='l_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
